### ISSUE TITLE
Apple Store Upload Error 

### ISSUE THREAD

**Issue by gurhangure** [AppliedRecognition/Ver-ID-UI-iOS#1]
Hi,

Im using Ver-ID-UI-iOS in my application and it works great but I get the following error when I upload my app to the store. Can you help me please ?

ERROR ITMS-90056: "This bundle Payload/MyAppName.app/Frameworks/VerIDCore.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

**Comment by jakubdolejs** [comment]
Thank you for reporting this @gurhangure. We'll update the dependency and let you know when a new version is available.

**Comment by jakubdolejs** [comment]
It will be ready tonight (Monday) or tomorrow morning (GMT)

**Comment by gurhangure** [comment]
Thank you very much.

**Comment by jakubdolejs** [comment]
Hello @gurhangure, 

Which version of the SDK are you using?

Do you mind sending me the Info.plist file from Pods/Ver-ID-Core/VerIDCore.framework/? I checked the most recent production version 1.12.4 and the Info.plist file contains a value for the key `CFBundleVersion`.

Thank you.

**Comment by gurhangure** [comment]
My Ver-ID-UI info.plist has values

Bundle version string (short) 1.12.1
Bundle version ${CURRENT_PROJECT_VERSION}

My Ver-ID-SDK-Identity info.plist values

Bundle version string (short) 3.0.1
Bundle version ${CURRENT_PROJECT_VERSION}

I figured out Ver-Id-Core info.plist does not have CFBundleVersion key, I manualy added it as "Bundle version ${CURRENT_PROJECT_VERSION}" and now error message has been changed new error message says

App Store Connect Operation Error
ERROR ITMS-90058: "This bundle is invalid. The value for key CFBundleVersion [${CURRENT_PROJECT_VERSION}] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

App Store Connect Operation Error
ERROR ITMS-90059: "This bundle Payload/Biosis E-Takip.app/Frameworks/VerIDCore.framework is invalid. The value for key CFBundleVersion [${CURRENT_PROJECT_VERSION}] in the Info.plist file must be no longer than 18 characters. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

it seems you need to tell me the value for the key.

**Comment by gurhangure** [comment]
My Ver-ID-UI info.plist has values

Bundle version string (short) 1.12.1
Bundle version ${CURRENT_PROJECT_VERSION}

My Ver-ID-SDK-Identity info.plist values

Bundle version string (short) 3.0.1
Bundle version ${CURRENT_PROJECT_VERSION}

I figured out Ver-Id-Core info.plist does not have CFBundleVersion key, I manualy added it as "Bundle version ${CURRENT_PROJECT_VERSION}" and now error message has been changed new error message says

App Store Connect Operation Error
ERROR ITMS-90058: "This bundle is invalid. The value for key CFBundleVersion [${CURRENT_PROJECT_VERSION}] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

App Store Connect Operation Error
ERROR ITMS-90059: "This bundle Payload/MyAppName.app/Frameworks/VerIDCore.framework is invalid. The value for key CFBundleVersion [${CURRENT_PROJECT_VERSION}] in the Info.plist file must be no longer than 18 characters. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

it seems you need to tell me the value for the key.

**Comment by jakubdolejs** [comment]
@gurhangure, have you tried updating to version 1.12.4? I know the plist for that version includes the CFBundleVersion value. You can also try using the short version string instead of `${CURRENT_PROJECT_VERSION}`, e.g., replace `${CURRENT_PROJECT_VERSION}` with `1.12.1`. If you enter `${CURRENT_PROJECT_VERSION}` into the plist Xcode will take it ad verbatim and it won't substitute it for the real version. Does that make sense?

**Comment by gurhangure** [comment]
I tried 1.12.1 instead of ${CURRENT_PROJECT_VERSION} and it worked ty.
